name: Taikoon UI Build and Checks

on: workflow_call

jobs:
  build:
    runs-on: [taiko-runner]
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install pnpm dependencies
        uses: ./.github/actions/install-pnpm-dependencies

      - name: Frontend build
        working-directory: ./packages/taikoon-ui
        run: |
          export $(cat .env.example | xargs)
          pnpm build

      - name: Svelte check
        working-directory: ./packages/taikoon-ui
        run: |
          export $(cat .env.example | xargs)
          pnpm check

      - name: Check formatting
        working-directory: ./packages/taikoon-ui
        run: pnpm lint

      - name: Unit tests
        env:
          SKIP_ENV_VALIDATION: "true"
        working-directory: ./packages/taikoon-ui
        run: pnpm test:unit
